[package]
name = "plurid_delog"
version = "0.0.0"
edition = "2018"
description = "client for centralized logging on a delog server"
repository = "https://github.com/plurid/delog"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://plurid.com"
documentation = "https://docs.rs/plurid_delog"
keywords = ["logging", "client", "cloud"]
categories = ["development-tools::debugging"]

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0"
serde_json = "1.0.64"
serde_repr = "0.1"
tokio = { version = "1", features = ["full"] }
