[package]
name = "delog"
version = "0.0.0"
edition = "2018"


[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0"
serde_json = "1.0.64"
serde_repr = "0.1"
tokio = { version = "1", features = ["full"] }
